// Regenerates campaign/dialogues/index.ts from the dialogue files in the
// directory, so the barrel can't fall out of sync with the files (no more
// "added a dialogue, forgot the export line"). Run: npm run gen-dialogues.
const fs = require("fs");
const path = require("path");

const dir = path.join(__dirname, "..", "campaign", "dialogues");
const files = fs
  .readdirSync(dir)
  .filter((f) => f.endsWith(".ts") && f !== "index.ts" && !f.endsWith(".test.ts"))
  .map((f) => f.replace(/\.ts$/, ""))
  .sort();

const header = "// GENERATED by scripts/genDialogueIndex.js — run `npm run gen-dialogues`.\n";
const body = files.map((f) => `export * from "./${f}";`).join("\n") + "\n";
fs.writeFileSync(path.join(dir, "index.ts"), header + body);
console.log(`wrote ${files.length} dialogue exports`);
