import * as Programs from "../../programs";
import { defineLevel } from "./_defineLevel";

const id = "ph-employee";
const map = `
......12-34...
..............
..............
..............
@------------A
--@---------B-
@------------C
..............
..............
..............
...56-78......
`;
const enemies = [Programs.GuardPup, Programs.Watchman, Programs.GuardPup];
const creditValues: number[] = [350, 350, 250, 330, 350, 330, 280, 330];

export default defineLevel(id, map, enemies, creditValues);

// 5#0:27