import * as Programs from "../../programs";
import { defineLevel } from "./_defineLevel";

const id = "tutorial";
const map = `
----------.......
----------.......
--@---A---.......
------a---.......
---@--a---.......
----------.......
----------.......
`;
const enemies = [Programs.Sentinel];
export default defineLevel(id, map, enemies);

// 1#1:20